# Generated by Django 3.2.12 on 2022-04-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author_id',
            new_name='author',
        ),
    ]
